blank_issues_enabled: true
contact_links:
  - name: Security reporting
    url: https://github.com/kouya-group/namegata-open-data/security/advisories/new
    about: Please use private reporting for vulnerabilities.

